on:
  push:
    branches: [ main ]

jobs:
  initial_job:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    - name: Run a command
      run: echo "This is the initial job."
  conditional_job:
    needs: initial_job # This job depends on completion of 'initial-job'
    runs-on: ubuntu-latest
    steps:
    - name: Execute on specific condition
      run: echo "This step runs because the condition is true."
      if: github.ref == 'refs/heads/main' # Condition to check if branch is 'main'

    - name: Alternative step for false condition
      run: echo "This step would run if the above condition was false."
      if: github.ref != 'refs/heads/main' # This condition is opposite of the above