on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm install
      - run: npm build
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: /path/to/build

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: build
          path: /path/to/build
      - run: ./deploy.sh