on:
  push:
    branches: [ main ]
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Set output
        run: echo "My output is: $MY_VARIABLE"
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: /path/to/artifact
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: my-artifact
          path: /path/to/download